################################################################################
# Substitutions
################################################################################
substitutions:
  name: led-clock-shelf
  friendly_name: LED Clock Shelf
  comment: DIY Machines Edge Clock
  area: Area
  ip_address: 192.168.x.x
  gateway: 192.168.x.x

################################################################################
# Platform
################################################################################
esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  area: ${area}
  name_add_mac_suffix: false

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .mydomain.com
  fast_connect: true
  power_save_mode: none
  manual_ip:
    static_ip: ${ip_address}
    gateway: ${gateway}
    subnet: 255.255.255.0
  ap:
    ssid: "${name}-fallback"
    password: !secret wifi_fallback_password

captive_portal:

mdns:

################################################################################
# LED Clock Shelf Main Configuration 
################################################################################
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Denver"

external_components:
  - source:
      type: local
      path: components

led_clock_shelf:
  id: led_clock
  pin: 21
  brightness: 128
  colon_style: 1
  time_id: homeassistant_time
  downlights_enabled: true
  light_sensor_pin: 34
  brightness_reduction_dark: 85  # 85% reduction in dark conditions
  brightness_transition_duration: 6000  # 6-second transition (in milliseconds)
  # colors:
  #   - name: "Bright Red"
  #     value: "#FF0000"
  #   - name: "Forest Green"
  #     value: [0, 128, 0]
  #   - name: "Deep Blue"
  #     value: "#0000FF"
  #   - name: "Sunset Orange"
  #     value: [255, 165, 0]

switch:
  - platform: led_clock_shelf
    id: display_switch
    name: "LED Clock Display Switch"
    parent_id: led_clock
    type: "display"
  - platform: led_clock_shelf
    id: downlights_switch
    name: "LED Clock Downlights Switch"
    parent_id: led_clock
    type: "downlights"

number:
  - platform: led_clock_shelf
    id: brightness_control
    name: "LED Clock Default Brightness"
    entity_category: config
    parent_id: led_clock
    min_value: 0
    max_value: 255
    step: 1

select:
  - platform: led_clock_shelf
    id: colon_style_select
    name: "LED Clock Colon Style"
    entity_category: config
    parent_id: led_clock
    type: "colon_style"
    options:
      - "None"
      - "Single"
      - "Dual"
  - platform: led_clock_shelf
    id: hour_color_select
    name: "LED Clock Hour Color"
    entity_category: config
    parent_id: led_clock
    type: "hour_color"
  - platform: led_clock_shelf
    id: minute_color_select
    name: "LED Clock Minute Color"
    entity_category: config
    parent_id: led_clock
    type: "minute_color"
  - platform: led_clock_shelf
    id: colon_color_select
    name: "LED Clock Colon Color"
    entity_category: config
    parent_id: led_clock
    type: "colon_color"
  - platform: led_clock_shelf
    id: downlight_color_select
    name: "LED Clock Downlight Color"
    entity_category: config
    parent_id: led_clock
    type: "downlight_color"

################################################################################
# Buttons & Sensors (Optional)
################################################################################
button:
  - platform: restart
    name: Restart
    icon: "mdi:restart"
    entity_category: diagnostic

button:
  - platform: safe_mode
    name: Safe Mode Boot
    icon: "mdi:restart"
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:
  - platform: uptime
    name: "Uptime Seconds"
    id: uptime_s
    update_interval: 60s
    
text_sensor:
  - platform: template
    name: "Uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 60s
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    state_class: measurement
    device_class: SIGNAL_STRENGTH
